### ISSUE TITLE
Allow time and frame number in `-b` `-e`, `-dt` option

### ISSUE THREAD

**Issue by PicoCentauri** [PicoCentauri/mda_cli#13]
In our current implementation the time is fixed to pico seconds. This is handy but users might also want to use a different time unit or even frame numbers. There are two options handling this

### Option 1

Ad a new paramater like `-u` for giving the unit for skipping etc. Allowed values could be `None` for frames, "ps" for pico seconds or even "ns" for nano seconds. 

### Option 2

Change the current parameters and parse the unit from the user input. I could think of something like

```bash
mda_cli xxx -b 10 -e 20 -dt 5 # frames
mda_cli xxx -b 10ps -e 20ps -dt 5ps # time
mda_cli xxx -b 10ps -e 20ns -dt 5ps # even different time units could be allowed
```

I'm preferring option 2 but are open for other opinions on this.

**Comment by joaomcteixeira** [comment]
I like a lot Option 2 as well. I vote for that :+1:

**Comment by PicoCentauri** [comment]
Okay then let's do it. I will file a PR asap
