### ISSUE TITLE
MDAnalysis docstrings not parsed properly

### ISSUE THREAD

**Issue by PicoCentauri** [PicoCentauri/mda_cli#2]
The current implementation of `numpydoc` does not work with the `MDAnalysis` docstrings. See the following code example

```python
from numpydoc.docscrape import NumpyDocString

class TestClass():
    r"""A TestClass docstring.

    Some long description

    Parameters
    ----------
    atomgroup : AtomGroup or UpdatingAtomGroup
            foo
    atomgroup2 : AtomGroup
            fancy second atomgroup
    """
    
doc = NumpyDocString(TestClass.__doc__)
print(len(doc["Parameters"]))
```

The output is 1 however there are 2 parameters in `TestClass `. When adding an extra line at the beginning of the docstring is parsed properly

```python
class TestClass():
    r"""
    A TestClass docstring.

    ...
```

Unfortunately I was not able to implement something like `doc = NumpyDocString("\n" + TestClass.__doc__)` quickly. Does somebody got an idea?

**Comment by joaomcteixeira** [comment]
I am trying to write a general parser we can use to read the docstrings. In the lines of Numpy doc but not so strict and focusing only on our requirements.

**Comment by joaomcteixeira** [comment]
I forgot to set PR #3 to close this issue.
It may be that we need to readdress this with minor modifications to accommodate edge cases on the documentation of the Analysis Classes. If that comes to be the case, we will revisit this issue.
